{% set version = "3.2" %}
{% set compiler = "gcc" %}
{% set compiler_version = "4.9.4" %}
{% set user_build = "edu159" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}

package:
  name: mpi4py
  version: 2.0.0

source:
  fn: mpi4py-2.0.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mpi4py/mpi4py-2.0.0.tar.gz
  md5: 4f7d8126d7367c239fd67615680990e3

build:
  number: 2
  string: {{ build_string }}
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python 2.7.*
    - mpich 3.2.* {{ build_string }}
  run:
    - python 2.7.*
    - mpich 3.2.* {{ build_string }}

test:
  imports:
    - mpi4py
    - mpi4py.MPI

about:
  home: http://mpi4py.scipy.org/
  license: BSD
  summary: Provides bindings of the MPI standard for Python
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: http://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py
