{% set name = "cplapp-lammps-stable" %}
{% set lammps_version = "11Aug17" %}
{% set compiler = os.getenv("CPL_CC") or "" %}
{% set compiler_version = os.getenv("CPL_CC_VERSION") or "" %}
{% set user_build = os.getenv("CPL_USER") or "" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}
{% set git_repo_name = "CPL_APP_LAMMPS-DEV" %}

package:
    name: {{ name }}
    version: {{ lammps_version }}
source:
    git_url: {{ os.getenv("CPL_GIT_REPO") or "" }}/{{ git_repo_name }}.git
    git_tag: {{ os.getenv("CPL_GIT_BRANCH") or "" }}
       
build:
    number: 0
    string: {{ build_string }}

requirements:
    build:
        - mpich 3.2.* {{ build_string }}
        - python 2.7.*
        - cpl 1.0.* {{ build_string }}
    run:
        - mpich 3.2.* {{ build_string }}
        - python 2.7.*
        - cpl 1.0.* {{ build_string }}
test:
    requires:
        - mpich 3.2.* {{ build_string }}
        - cpl 1.0.* {{ build_string }}
        - cplpy 1.0.* {{ build_string }}
    source_files :
        - test
    commands:
        - py.test -v test
extra:
    sources:
        LAMMPS-STABLE:
            fn: lammps-{{ lammps_version }}.tar.gz 
            url: http://lammps.sandia.gov/tars/lammps-{{ lammps_version }}.tar.gz
    recipe-maintainers:
        - edu159
about:
    home: http://cpl-library.org
license: GPL3
