{% set name = "cplapp-lammps-stable" %}
{% set lammps_version = "11Aug17" %}
{% set compiler = "gcc" %}
{% set compiler_version = "7.2.1" %}
{% set user_build = "edu159" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}

package:
    name: {{ name }}
    version: {{ lammps_version }}
source:
    git_url: https://github.com/Crompulence/CPL_APP_LAMMPS-DEV.git
    git_tag: edu159
       
build:
    number: 0
    string: {{ build_string }}

requirements:
    build:
        - mpich 3.2.* {{ build_string }}
        - python 2.7.*
        - cpl 1.0.* {{ build_string }}
    run:
        - mpich 3.2.* {{ build_string }}
        - python 2.7.*
        - cpl 1.0.* {{ build_string }}
test:
    requires:
        - mpich 3.2.* {{ build_string }}
        - cpl 1.0.* {{ build_string }}
        - cplpy 1.0.* {{ build_string }}
    source_files :
        - test
    commands:
        - py.test -s -v ./test/velocityP-C
extra:
    sources:
        LAMMPS-STABLE:
            fn: lammps-{{ lammps_version }}.tar.gz 
            url: http://lammps.sandia.gov/tars/lammps-{{ lammps_version }}.tar.gz
    recipe-maintainers:
        - edu159
about:
    home: http://cpl-library.org
license: GPL3
