{% set version = "3.2" %}
{% set compiler = os.getenv("CPL_CC") or "" %}
{% set compiler_version = os.getenv("CPL_CC_VERSION") or "" %}
{% set user_build = os.getenv("CPL_USER") or "" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}

package:
    name: mpich
    version: {{ version }}

source:
    fn: mpich-{{ version }}.tar.gz
    url: http://www.mpich.org/static/downloads/{{ version }}/mpich-{{ version }}.tar.gz
    sha256: 0778679a6b693d7b7caff37ff9d2856dc2bfc51318bf8373859bfa74253da3dc

build:
    number: 4
    string: {{ build_string }}

requirements:
    build:
        - libgcc-ng {{ compiler_version }}
        - gcc_linux-64 {{ compiler_version }}
        - gxx_linux-64 {{ compiler_version }}
        - gfortran_linux-64 {{ compiler_version }}

    run:
        - libgcc-ng
        - libgfortran-ng
        - libstdcxx-ng

test:
    requires:
        - libgcc-ng {{ compiler_version }}
        - gcc_linux-64 {{ compiler_version }}
        - gxx_linux-64 {{ compiler_version }}
        - gfortran_linux-64 {{ compiler_version }}


    files:
        - tests/helloworld.c
        - tests/helloworld.cxx
        - tests/helloworld.f
        - tests/helloworld.f90
    commands:
        - conda inspect linkages mpich

about:
    home: http://www.mpich.org/
    license: MPICH
    license_file: COPYRIGHT
    license_family: Other
    summary: 'A high performance widely portable implementation of the MPI standard.'
    description: |
      MPICH is a high performance and widely portable implementation of the
      Message Passing Interface (MPI) standard.
    doc_url: http://www.mpich.org/documentation/guides
    dev_url: https://wiki.mpich.org/mpich/index.php/Main_Page

extra:
    recipe-maintainers:
        - edu159
