{% set version = "1.0" %}
{% set compiler = os.getenv("CPL_CC") or "" %}
{% set compiler_version = os.getenv("CPL_CC_VERSION") or "" %}
{% set user_build = os.getenv("CPL_USER") or "" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}
{% set git_repo_name = "cplutils" %}

package:
    name: cplutils
    version: {{ version }}
source:
    git_url: {{ os.getenv("CPL_GIT_REPO") or "" }}/{{ git_repo_name }}.git
    git_tag: {{ os.getenv("CPL_GIT_BRANCH") or "" }}
build:
    number: 0
    string: {{ build_string }}
requirements:
    build:
        - python 2.7.* 
        - setuptools
    run:
        - python 2.7.* 
        - pyfoam 0.6.6
        - numpy 1.13.*
        - scipy 1.0.*
        - moltemplate 2.8.1
        - packmol
# test:
#     requires:
#         - python 2.7.*
#         - pytest 2.9.*
#         - numpy 1.13.*
#         - scipy 1.0.*
#         - pyfoam 0.6.6
about:
    home: http://www.cpl-library.org
license: GPL3
