{% set name = "openfoam" %}
{% set version = "3.0.1" %}
{% set src_md5 = "304e6a14b9e69c20989527f5fb1ed724" %}
{% set thirdparty_md5 = "4665072d7d29ab9af5ced402f667185a" %}
{% set build_mode = "download" %}
{% set compiler = os.getenv("CPL_CC") or "" %}
{% set compiler_version = os.getenv("CPL_CC_VERSION") or "" %}
{% set user_build = os.getenv("CPL_USER") or "" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}

package:
    name: {{ name }}
    version: {{ version }}
source:
    {% if build_mode == "download" %}
    fn: OpenFOAM-{{ version }}.tgz
    url: https://sourceforge.net/projects/foam/files/foam/{{ version }}/OpenFOAM-{{ version }}.tgz
    md5: {{ src_md5 }}
    patches:
        - ptscotchDecomp.patch
        - bashrc.patch
        - cshrc.patch
    folder: OpenFOAM-{{ version }}
    {% else %}
    path: /build/edu159/miniconda2/conda-bld/openfoam_1516035375344/work
    {% endif %}
       
build:
    number: 0
    string: {{ build_string }}
    rpaths:
        - lib/
        - lib/openfoam-scotch

requirements:
    build:
        - python 2.7.*
        - mpich 3.2.* {{ build_string }}
        - libboost 1.67.*
        - flex 2.5.* {{ build_string }}
        - bison
        - zlib 
        - cmake 3.*.* 
        - gmp >=6.1.0
        - mpfr >=3.1.5
        - gcc_linux-64 {{ compiler_version }}
        - gxx_linux-64 {{ compiler_version }}
        - gfortran_linux-64 {{ compiler_version }}

    run:
        - mpich 3.2.* {{ build_string }}
        - libboost 1.67.*
        - gmp >=6.1.0
        - mpfr >=3.1.5
        - flex 2.5.* {{ build_string }}
        - zlib 
        - libgcc-ng {{ compiler_version }}
        - libgfortran-ng {{ compiler_version }}
        - libstdcxx-ng {{ compiler_version }}

extra:
    {% if build_mode == "download" %}
    sources:
        ThirdParty-{{ version }}:
            fn: ThirdParty-{{ version }}.tgz
            url: https://sourceforge.net/projects/foam/files/foam/{{ version }}/ThirdParty-{{ version }}.tgz
            md5: {{ thirdparty_md5 }}
    {% endif %}
    recipe-maintainers:
        - edu159

 
about:
    home: https://openfoam.org
license: GPL3
