{% set name = "openfoam" %}
{% set version = "3.0.1" %}
{% set src_md5 = "304e6a14b9e69c20989527f5fb1ed724" %}
{% set thirdparty_md5 = "4665072d7d29ab9af5ced402f667185a" %}
{% set build_mode = "download" %}

package:
    name: {{ name }}
    version: {{ version }}
source:
    {% if build_mode == "download" %}
    fn: OpenFOAM-{{ version }}.tgz
    url: https://sourceforge.net/projects/foam/files/foam/{{ version }}/OpenFOAM-{{ version }}.tgz
    md5: {{ src_md5 }}
    patches:
        - ptscotchDecomp.patch
    {% else %}
    path: /home/edu/miniconda2/conda-bld/openfoam_1494875081741/work
    {% endif %}
       
build:
    number: 0
    rpaths:
        - lib/
        - lib/openfoam-scotch

requirements:
    build:
        - gcc
        - toolchain
        - mpich 3.2.*
    run:
        - mpich 3.2.*
extra:
    {% if build_mode == "download" %}
    sources:
        3rdparty:
            fn: ThirdParty-{{ version }}.tgz
            url: https://sourceforge.net/projects/foam/files/foam/{{ version }}/ThirdParty-{{ version }}.tgz
            md5: {{ thirdparty_md5 }}
    {% endif %}
    recipe-maintainers:
        - edu159

 
about:
    home: https://openfoam.org
license: GPL3
