{% set version = "1.0" %}
{% set compiler = "gcc" %}
{% set compiler_version = "4.9.4" %}
{% set user_build = "edu159" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}

package:
    name: cplpy
    version: {{ version }}
source:
    git_url: https://github.com/Crompulence/cpl-library.git
    git_tag: edu159
build:
    number: 0
    string: {{ build_string }}
requirements:
    build:
        - cpl >=1.0 {{ build_string }}
        - mpich 3.2.* {{ build_string }}
        - python 2.7.*
        - pytest 2.9.*
        - mpi4py >=2.0.0 {{ build_string }}
        - numpy
    run:
        - cpl >=1.0 {{ build_string }}
        - mpich 3.2* {{ build_string }}
        - python 2.7.* 
        - pytest 2.9.*
        - mpi4py >=2.0.0 {{ build_string }}
        - numpy
test:
    requires:
        - cpl >=1.0 {{ build_string }}
        - python 2.7.*
        - pytest 2.9.*
        - mpi4py >=2.0.0 {{ build_string }}
        - numpy
about:
    home: http://www.cpl-library.org
license: GPL3
