{% set name = "boost-dev" %}
{% set version = "1.60" %}
{% set version_ = "1_60" %}
package:
    name: {{ name }}
    version: {{ version }}
source:
    fn: boost_1_60_0.tar.gz
    url: http://sourceforge.net/projects/boost/files/boost/{{ version }}.0/boost_{{ version_ }}_0.tar.gz
build:
    number: 0
about:
    home: http://www.boost.org 
license: Boost Software License
