{% set version = "2.5.39" %}
{% set compiler = os.getenv("CPL_CC") or "" %}
{% set compiler_version = os.getenv("CPL_CC_VERSION") or "" %}
{% set user_build = os.getenv("CPL_USER") or "" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}

package:
  name: flex
  version: {{ version }}

source:
  fn: flex-{{ version }}.tar.gz
  url: http://sourceforge.net/projects/flex/files/flex-{{ version }}.tar.gz
  md5: e133e9ead8ec0a58d81166b461244fde
  patches:
    # Patch the Makefile.am based on a bug report on SourceForge.
    # https://sourceforge.net/p/flex/bugs/182/
    - Makefile.am.patch
    # Patch the Makefile.am based on a bug report on SourceForge.
    # https://sourceforge.net/p/flex/bugs/169/
    - 0001-bison-test-fixes-Do-not-use-obsolete-bison-construct.patch

build:
  skip: true  # [win]
  number: 0
  string: {{ build_string }}
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libgcc-ng {{ compiler_version }}
    - gcc_linux-64 {{ compiler_version }}
    - gxx_linux-64 {{ compiler_version }}
    - gfortran_linux-64 {{ compiler_version }}
    - autoconf
    - automake
    - libiconv
    - libtool
    - m4
    - bison

  run:
    - libiconv
    - m4

test:
  commands:
    # CLI tests
    - flex --help

    # Include test
    - test -f ${PREFIX}/include/FlexLexer.h

    # Lib tests
    - test -f ${PREFIX}/lib/libfl.a
    - test -f ${PREFIX}/lib/libfl_pic.a
    - test -f ${PREFIX}/lib/libfl.dylib      # [osx]
    - test -f ${PREFIX}/lib/libfl_pic.dylib  # [osx]
    - test -f ${PREFIX}/lib/libfl.so         # [linux]
    - test -f ${PREFIX}/lib/libfl_pic.so     # [linux]

about:
  home: http://flex.sourceforge.net/
  license: BSD 2-Clause
  summary: The Fast Lexical Analyzer

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
