{% set name = "moltemplate" %}
{% set version = "2.8.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "712c405579328d1a3f4c263618d0d7ffdb00947e7f411c96ee0fcd2e02e9d7d7" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - ttree.py=moltemplate.ttree:main
    - ttree_render.py=moltemplate.ttree_render:main
    - bonds_by_type.py=moltemplate.bonds_by_type:main
    - chargepairs_by_type.py=moltemplate.chargepairs_by_type:main
    - dump2data.py=moltemplate.dump2data:main
    - extract_espresso_atom_types.py=moltemplate.extract_espresso_atom_types:main
    - extract_lammps_data.py=moltemplate.extract_lammps_data:main
    - ettree.py=moltemplate.ettree:main
    - genpoly.py=moltemplate.ettree:main
    - ltemplify.py=moltemplate.ltemplify:main
    - lttree.py=moltemplate.lttree:main
    - lttree_check.py=moltemplate.lttree_check:main
    - lttree_postprocess.py=moltemplate.lttree_postprocess:main
    - nbody_by_type.py=moltemplate.nbody_by_type:main
    - nbody_fix_ttree_assignments.py=moltemplate.nbody_fix_ttree_assignments:main
    - nbody_reorder_atoms.py=moltemplate.nbody_reorder_atoms:main
    - pdbsort.py=moltemplate.pdbsort:main
    - postprocess_input_script.py=moltemplate.postprocess_input_script:main
    - postprocess_coeffs.py=moltemplate.postprocess_coeffs:main
    - raw2data.py=moltemplate.raw2data:main
    - remove_duplicate_atoms.py=moltemplate.remove_duplicate_atoms:main
    - remove_duplicates_nbody.py=moltemplate.remove_duplicates_nbody:main
    - renumber_DATA_first_column.py=moltemplate.renumber_DATA_first_column:main
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python 2.7.*
    - setuptools
    - pytest-runner
  run:
    - python 2.7.*

test:
  imports:
    - moltemplate
    - moltemplate.nbody_alt_symmetry
#  commands:
#    - ttree.py --help
#    - ttree_render.py --help
#    - bonds_by_type.py --help
#    - chargepairs_by_type.py --help
#    - dump2data.py --help
#    - extract_espresso_atom_types.py --help
#    - extract_lammps_data.py --help
#    - ettree.py --help
#    - genpoly.py --help
#    - ltemplify.py --help
#    - lttree.py --help
#    - lttree_check.py --help
#    - lttree_postprocess.py --help
#    - nbody_by_type.py --help
#    - nbody_fix_ttree_assignments.py --help
#    - nbody_reorder_atoms.py --help
#    - pdbsort.py --help
#    - postprocess_input_script.py --help
#    - postprocess_coeffs.py --help
#    - raw2data.py --help
#    - remove_duplicate_atoms.py --help
#    - remove_duplicates_nbody.py --help
#    - renumber_DATA_first_column.py --help
  requires:
    - pytest
    - pytest-runner

about:
  home: https://github.com/jewettaij/moltemplate
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: A general cross-platform text-based molecule builder for LAMMPS
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
