{% set version = "1.0" %}
{% set compiler = os.getenv("CPL_CC") or "" %}
{% set compiler_version = os.getenv("CPL_CC_VERSION") or "" %}
{% set user_build = os.getenv("CPL_USER") or "" %}
{% set build_string = user_build+"_"+compiler+compiler_version %}
{% set git_repo_name = "cpl-library" %}

package:
    name: cpl
    version: {{ version }}
source:
    git_url: {{ os.getenv("CPL_GIT_REPO") or "" }}/{{ git_repo_name }}.git
    git_tag: {{ os.getenv("CPL_GIT_BRANCH") or "" }}
build:
    number: 0
    string: {{ build_string }}

requirements:
    build:
        - mpich 3.2.* {{ build_string }}
    run:
        - mpich 3.2.* {{ build_string }}
test:
    requires:
        - python 2.7.*
        - pytest 2.9.*
        - mpi4py >=2.0.0 {{ build_string }}
        - numpy
        - cplpy 1.0.* {{ build_string }}
    commands :
        - cpltest all
about:
    home: http://www.cpl-library.org
license: GPL3
