package:
    name: cpl
    version: "1.0"
source:
    git_url: https://github.com/Crompulence/cpl-library.git
    git_tag: edu159
build:
    number: 0
    string: edu159

requirements:
    build:
        - mpich 3.2
    run:
        - mpich 3.2
test:
    requires:
        - python 2.7.*
        - pytest 2.9.*
        - mpi4py >=2.0.0
        - numpy
        - cplpy
    commands :
        - cpltest all
about:
    home: http://www.cpl-library.org
license: GPL3
